### ISSUE TITLE
Suggestion: VRMLoader.load should return a promise?

### ISSUE THREAD

**Issue by stonecauldron** [rdrgn/three-vrm#9]
Since VRMloader loads the model asynchronously it might make more sense for it to return a promise?

**Comment by reminjp** [comment]
Since loaders in three.js (e.g. [FileLoader](https://github.com/mrdoob/three.js/blob/ce501ae22b51665646a8d4a8a7131d78cc54005f/src/loaders/FileLoader.js#L18), [GLTFLoader](https://github.com/mrdoob/three.js/blob/ce501ae22b51665646a8d4a8a7131d78cc54005f/examples/js/loaders/GLTFLoader.js#L24)) employ callbacks, I made the `VRMLoader.load` function with current args.

However, it is true that the current form is difficult to read/understand. It may not be necessary to obey the style of three.js.

🤔 thinking...

**Comment by rdrgn** [comment]
I want to improve the structure of `VRM` class. I might also modify `VRMLoader` at the same time.

**Comment by stonecauldron** [comment]
I think the three.js style is mainly due to browser compatibility concerns. They also only use `var` variable declarations for example.

So it might not be too problematic to deviate from their style in this case 🤔
